### ISSUE TITLE
Latest version does not work on node4 anymore.

### ISSUE THREAD

**Issue by Raynos** [alexgorbatchev/node-crc#46]
```
/home/raynos/uber/tchannel-node/node_modules/crc/lib/crc32.js:21
  if (!_buffer.Buffer.isBuffer(buf)) buf = (0, _create_buffer2.default)(buf);
                                                                       ^

TypeError: this is not a typed array.
    at from (native)
    at /home/raynos/uber/tchannel-node/node_modules/crc/lib/crc32.js:21:72
    at fn (/home/raynos/uber/tchannel-node/node_modules/crc/lib/define_crc.js:9:12)
    at Object.<anonymous> (/home/raynos/uber/tchannel-node/test/v2/args.js:104:48)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Object.Module._extensions.(anonymous function) [as .js] (/home/raynos/uber/tchannel-node/node_modules/istanbul/lib/hook.js:109:37)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
```

Node version, v4.4.7

**Comment by alexgorbatchev** [comment]
Thanks for heads up. How do you think I should fix this?

**Comment by Raynos** [comment]
```
> Buffer.from.toString()
'function from() { [native code] }'
```

```
Object.setPrototypeOf(Buffer.prototype, Uint8Array.prototype);
```

Your "detection" for `Buffer.from` finds `Uint8Array.from` instead of `Buffer.from`.

I would revert that commit that uses `Buffer.from` and stick to `new Buffer(x)`

**Comment by alexgorbatchev** [comment]
Sigh... `new Buffer(x)` is [deprecated since 6.x](https://nodejs.org/api/buffer.html#buffer_new_buffer_array)... I'll try using [safe-buffer](https://www.npmjs.com/package/safe-buffer)

**Comment by alexgorbatchev** [comment]
Published a fix, see 2816ce112ad66534f241c903ad98eec58b13b790 (I used Buffer detection from `safe-buffer`)

**Comment by Raynos** [comment]
Herp derp. who decided to deprecate `new Buffer()` that is dumb :(

**Comment by alexgorbatchev** [comment]
https://github.com/ChALkeR/notes/blob/master/Buffer-knows-everything.md
